# Generated by Django 5.2.5 on 2026-06-01 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, unique=True, verbose_name='اسلاگ')),
                ('image', models.URLField(blank=True, verbose_name='تصویر')),
                ('image_file', models.ImageField(blank=True, upload_to='artists/', verbose_name='فایل تصویر')),
                ('bio', models.TextField(blank=True, verbose_name='بیوگرافی')),
                ('song_count', models.PositiveIntegerField(default=0, verbose_name='تعداد آثار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
            ],
            options={
                'verbose_name': 'هنرمند',
                'verbose_name_plural': 'هنرمندان',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('duration_days', models.PositiveIntegerField(verbose_name='مدت (روز)')),
                ('download_limit', models.PositiveIntegerField(verbose_name='محدودیت دانلود')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت (تومان)')),
                ('icon', models.CharField(default='zap', max_length=50, verbose_name='آیکون')),
                ('gradient', models.CharField(default='from-purple-600 to-indigo-600', max_length=200, verbose_name='گرادینت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_popular', models.BooleanField(default=False, verbose_name='محبوب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
            ],
            options={
                'verbose_name': 'طرح اشتراک',
                'verbose_name_plural': 'طرح\u200cهای اشتراک',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت (تومان)')),
                ('cover', models.URLField(blank=True, verbose_name='تصویر')),
                ('cover_file', models.ImageField(blank=True, upload_to='songs/covers/', verbose_name='فایل تصویر')),
                ('preview_url', models.URLField(blank=True, verbose_name='لینک پیش\u200cنمایش')),
                ('audio_file', models.FileField(blank=True, upload_to='songs/audio/', verbose_name='فایل صوتی')),
                ('is_published', models.BooleanField(default=True, verbose_name='منتشر شده')),
                ('is_best_seller', models.BooleanField(default=False, verbose_name='پرفروش')),
                ('is_popular', models.BooleanField(default=False, verbose_name='پرطرفدار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music.artist', verbose_name='هنرمند')),
            ],
            options={
                'verbose_name': 'آهنگ',
                'verbose_name_plural': 'آهنگ\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('cover', models.URLField(blank=True, verbose_name='تصویر')),
                ('cover_file', models.ImageField(blank=True, upload_to='albums/', verbose_name='فایل تصویر')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت (تومان)')),
                ('is_published', models.BooleanField(default=True, verbose_name='منتشر شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('songs', models.ManyToManyField(blank=True, related_name='albums', to='music.song', verbose_name='آهنگ\u200cها')),
            ],
            options={
                'verbose_name': 'آلبوم',
                'verbose_name_plural': 'آلبوم\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
