# Generated by Django 5.2.5 on 2026-06-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='arranged_audio',
            field=models.URLField(blank=True, help_text='نسخه تنظیم جدید - فقط برای خریداران', verbose_name='لینک تنظیم جدید'),
        ),
        migrations.AddField(
            model_name='song',
            name='bpm',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='BPM'),
        ),
        migrations.AddField(
            model_name='song',
            name='composer',
            field=models.CharField(blank=True, max_length=200, verbose_name='آهنگساز'),
        ),
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.CharField(blank=True, help_text='مثلاً 3:45', max_length=10, verbose_name='مدت زمان'),
        ),
        migrations.AddField(
            model_name='song',
            name='lyricist',
            field=models.CharField(blank=True, max_length=200, verbose_name='ترانه\u200cسرا'),
        ),
        migrations.AddField(
            model_name='song',
            name='musical_key',
            field=models.CharField(blank=True, help_text='مثلاً C major, A minor', max_length=50, verbose_name='گام'),
        ),
        migrations.AddField(
            model_name='song',
            name='original_audio',
            field=models.URLField(blank=True, help_text='نسخه اصلی - رایگان برای همه', verbose_name='لینک آهنگ اصلی'),
        ),
        migrations.AlterField(
            model_name='song',
            name='preview_url',
            field=models.URLField(blank=True, help_text='نسخه دمو - رایگان برای همه', verbose_name='لینک دمو'),
        ),
    ]
