# Generated by Django 5.2.5 on 2026-06-02 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_usersubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(choices=[('demo', 'دمو'), ('original', 'اصلی'), ('arranged', 'تنظیم جدید')], max_length=20, verbose_name='نسخه')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان دانلود')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='music.song', verbose_name='آهنگ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'دانلود کاربر',
                'verbose_name_plural': 'دانلودهای کاربران',
                'ordering': ['-downloaded_at'],
            },
        ),
    ]
