# Generated by Django 5.2.5 on 2026-06-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_userdownload'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='purchase_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد خرید'),
        ),
        migrations.AddField(
            model_name='song',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید'),
        ),
    ]
