# Generated by Django 5.2.14 on 2026-06-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='description',
            field=models.TextField(blank=True, help_text='توضیح کامل درباره آهنگ (برای SEO)', verbose_name='توضیحات'),
        ),
    ]
