# Generated by Django 5.2.14 on 2026-06-04 08:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_song_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='توضیح کامل درباره آهنگ (برای SEO)', verbose_name='توضیحات'),
        ),
    ]
