# Generated by Django 5.2.14 on 2026-06-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_alter_song_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='lyrics',
            field=models.TextField(blank=True, help_text='متن کامل ترانه', verbose_name='متن آهنگ'),
        ),
    ]
