# Generated by Django 5.2.14 on 2026-06-04 16:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_add_lyrics_to_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='بیوگرافی'),
        ),
    ]
