# Generated by Django 5.2.14 on 2026-06-04 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_add_ckeditor_to_artist_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='song_count',
        ),
    ]
