# Generated by Django 5.2.14 on 2026-06-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_remove_song_count_from_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('artist_name', models.CharField(max_length=200, verbose_name='نام هنرمند')),
                ('cover_url', models.URLField(blank=True, verbose_name='تصویر')),
                ('mp3_url', models.URLField(blank=True, verbose_name='لینک دانلود')),
                ('source_url', models.URLField(help_text='آدرس صفحه جزئیات آهنگ', unique=True, verbose_name='لینک مبدأ')),
                ('slug', models.CharField(blank=True, max_length=200, verbose_name='اسلاگ')),
                ('date_str', models.CharField(blank=True, max_length=100, verbose_name='تاریخ انتشار')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='تعداد دانلود')),
                ('is_imported', models.BooleanField(default=False, verbose_name='وارد شده به آهنگ\u200cهای اصلی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
            ],
            options={
                'verbose_name': 'آهنگ اسکرپ شده',
                'verbose_name_plural': 'آهنگ\u200cهای اسکرپ شده',
                'ordering': ['-created_at'],
            },
        ),
    ]
