# Generated by Django 5.2.14 on 2026-06-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_song_instruments_file_song_separate_instruments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='separate_instruments',
        ),
        migrations.RemoveField(
            model_name='song',
            name='separation_status',
        ),
        migrations.AddField(
            model_name='scrapedsong',
            name='separate_instruments',
            field=models.BooleanField(default=False, help_text='فعالسازی تفکیک وکال و ساز با MDX-Net و ساخت آهنگ جدید', verbose_name='تفکیک سازها'),
        ),
        migrations.AddField(
            model_name='scrapedsong',
            name='separation_status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('processing', 'در حال پردازش'), ('done', 'انجام شده'), ('failed', 'خطا')], default='pending', max_length=20, verbose_name='وضعیت تفکیک'),
        ),
        migrations.AlterField(
            model_name='song',
            name='instruments_file',
            field=models.URLField(blank=True, help_text='لینک فایل سازهای تفکیک شده', verbose_name='فایل سازها'),
        ),
    ]
