# Generated by Django 5.2.14 on 2026-06-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_remove_song_separate_instruments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedsong',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='پیام خطا'),
        ),
    ]
