# Generated by Django 5.2.14 on 2026-06-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0016_scrapedsong_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='demo_file',
            field=models.FileField(blank=True, help_text='دموی ۱ دقیقه\u200cای', upload_to='songs/demos/', verbose_name='فایل دمو'),
        ),
    ]
