# Generated by Django 5.2.14 on 2026-06-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0017_song_demo_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='demo_file',
        ),
        migrations.AlterField(
            model_name='song',
            name='arranged_audio',
            field=models.FileField(blank=True, help_text='خروجی تفکیک سازها - فقط برای خریداران', upload_to='songs/arranged/', verbose_name='فایل تنظیم جدید'),
        ),
        migrations.AlterField(
            model_name='song',
            name='cover',
            field=models.FileField(blank=True, upload_to='songs/covers/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='song',
            name='original_audio',
            field=models.FileField(blank=True, upload_to='songs/audio_original/', verbose_name='فایل آهنگ اصلی'),
        ),
        migrations.AlterField(
            model_name='song',
            name='preview_url',
            field=models.FileField(blank=True, help_text='دموی ۱ دقیقه\u200cای - رایگان برای همه', upload_to='songs/demos/', verbose_name='فایل دمو'),
        ),
    ]
