# Generated by Django 5.2.14 on 2026-06-06 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0018_remove_song_demo_file_alter_song_arranged_audio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='cover_file',
        ),
        migrations.RemoveField(
            model_name='song',
            name='instruments_file',
        ),
    ]
