# Generated by Django 5.2.14 on 2026-06-06 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0019_remove_song_cover_file_remove_song_instruments_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='audio_file',
        ),
    ]
