# Generated by Django 5.2.5 on 2026-06-01 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, unique=True, verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, unique=True, verbose_name='اسلاگ')),
                ('excerpt', models.TextField(blank=True, verbose_name='خلاصه')),
                ('content', models.TextField(blank=True, verbose_name='محتوا')),
                ('image', models.URLField(blank=True, verbose_name='تصویر')),
                ('image_file', models.ImageField(blank=True, upload_to='blog/', verbose_name='فایل تصویر')),
                ('date_published', models.DateField(verbose_name='تاریخ انتشار')),
                ('is_published', models.BooleanField(default=True, verbose_name='منتشر شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'پست وبلاگ',
                'verbose_name_plural': 'پست\u200cهای وبلاگ',
                'ordering': ['-date_published'],
            },
        ),
    ]
