# Generated by Django 5.2.14 on 2026-06-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_add_ckeditor_to_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='reading_time',
            field=models.PositiveSmallIntegerField(default=0, help_text='در صورت خالی گذاشتن، خودکار محاسبه می\u200cشود', verbose_name='زمان مطالعه (دقیقه)'),
        ),
    ]
