# Generated by Django 5.2.5 on 2026-06-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_line1', models.CharField(max_length=200, verbose_name='خط اول عنوان')),
                ('title_line2', models.CharField(max_length=200, verbose_name='خط دوم عنوان')),
                ('title_line3', models.CharField(blank=True, max_length=200, verbose_name='خط سوم عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('badge_icon', models.CharField(default='music', max_length=50, verbose_name='آیکون نشان')),
                ('badge_text', models.CharField(max_length=200, verbose_name='متن نشان')),
                ('gradient_name', models.CharField(default='from-purple-400 via-indigo-400 to-cyan-400', max_length=200, verbose_name='گرادینت')),
                ('glow_color', models.CharField(default='bg-purple-600/20', max_length=100, verbose_name='رنگ درخشش')),
                ('bg_image', models.URLField(blank=True, verbose_name='تصویر پس\u200cزمینه')),
                ('bg_image_file', models.ImageField(blank=True, upload_to='hero/', verbose_name='فایل تصویر پس\u200cزمینه')),
                ('btn1_text', models.CharField(blank=True, max_length=100, verbose_name='متن دکمه اول')),
                ('btn1_link', models.CharField(blank=True, max_length=200, verbose_name='لینک دکمه اول')),
                ('btn1_gradient', models.CharField(blank=True, max_length=200, verbose_name='گرادینت دکمه اول')),
                ('btn1_icon', models.CharField(blank=True, max_length=50, verbose_name='آیکون دکمه اول')),
                ('btn2_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='متن دکمه دوم')),
                ('btn2_link', models.CharField(blank=True, max_length=200, null=True, verbose_name='لینک دکمه دوم')),
                ('btn2_icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='آیکون دکمه دوم')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
            ],
            options={
                'verbose_name': 'اسلاید هدر',
                'verbose_name_plural': 'اسلایدهای هدر',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='کلید')),
                ('value', models.TextField(blank=True, verbose_name='مقدار')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('text', models.TextField(verbose_name='متن')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='امتیاز')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
                'ordering': ['sort_order'],
            },
        ),
    ]
