# Generated by Django 5.2.5 on 2026-06-02 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_comment_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_testimonial',
            field=models.BooleanField(default=False, help_text='با فعال\u200cسازی در بخش نظرات صفحه اصلی نمایش داده می\u200cشود', verbose_name='نمایش در صفحه اصلی'),
        ),
    ]
