# Generated by Django 5.2.5 on 2026-06-02 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_comment_is_testimonial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
