# Generated by Django 5.2.14 on 2026-06-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_advertisement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='image',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
    ]
