# Generated by Django 5.2.5 on 2026-06-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='authority',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='کد مرجع زرین\u200cپال'),
        ),
        migrations.AddField(
            model_name='order',
            name='ref_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='شناسه تراکنش'),
        ),
    ]
