# Generated by Django 5.2.14 on 2026-06-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_order_authority_order_ref_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد تخفیف')),
                ('discount_type', models.CharField(choices=[('percent', 'درصد'), ('fixed', 'مبلغ ثابت')], default='percent', max_length=10, verbose_name='نوع تخفیف')),
                ('value', models.PositiveIntegerField(help_text='درصد (۱-۱۰۰) یا مبلغ ثابت به تومان', verbose_name='مقدار تخفیف')),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='۰ = نامحدود', verbose_name='حداکثر استفاده')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='تعداد استفاده')),
                ('min_order_amount', models.PositiveIntegerField(default=0, help_text='۰ = بدون حداقل', verbose_name='حداقل مبلغ سفارش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کدهای تخفیف',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='کد تخفیف'),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_discount',
            field=models.PositiveIntegerField(default=0, verbose_name='تخفیف'),
        ),
    ]
